const actionTypes = {
    CREATE_CATEGORY: 'CREATE_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',

    CREATE_LOCATION: 'CREATE_LOCATION',
    UPDATE_LOCATION: 'UPDATE_LOCATION',
    DELETE_LOCATION: 'DELETE_LOCATION',
};

export default actionTypes;