const actionTypes = {
    SELECT_CATEGORY: 'SELECT_CATEGORY',
    TOGGLE_ADD_CATEGORY_MODAL: 'TOGGLE_ADD_CATEGORY_MODAL',
    TOGGLE_EDIT_CATEGORY_MODAL: 'TOGGLE_EDIT_CATEGORY_MODAL',
    UPDATE_CATEGORY_MODAL_TEXT_FIELD: 'UPDATE_CATEGORY_MODAL_TEXT_FIELD',

    CREATE_CATEGORY: 'CREATE_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',


    CREATE_LOCATION: 'CREATE_LOCATION',
    UPDATE_LOCATION: 'UPDATE_LOCATION',
    DELETE_LOCATION: 'DELETE_LOCATION',
};

export default actionTypes;